### ISSUE TITLE
Question about webextension-polyfill insertion using content-script

### ISSUE THREAD

**Issue by BoQsc** [mozilla/webextension-polyfill#106]
If, this polyfill is inserted into every webpage using content-script, could it break other extensions that do not use or are aligned to webextension-polyfill? For example - in a chrome browser?

**Comment by Rob--W** [comment]
This polyfill should not be inserted in a web page because there are no WebExtension APIs in a web page. You will not get a cross-browser-compatible extension if you try to use a `chrome.` or `browser.` API from a web page.

The polyfill is a no-op when the `browser` global is detected, so in theory there won't be conflicts if multiple extensions use the polyfill in a web page. But I recommend to not use the polyfill in a web page for the above reason (and to minimize impacts on the page itself. E.g. if the page has a `browser` variable, then your extension will break anyway).

**Comment by BoQsc** [comment]
So, just to be more clear: as long as declaring this polyfill inside extension's manifest will inject the polyfil into Isolated World that has access only to the page elements. polyfill Injection actually has no effect on the other extensions that are running.
