### ISSUE TITLE
Chrome requires an iconUrl when creating a notification

### ISSUE THREAD

**Issue by straurob** [mozilla/webextension-polyfill#117]
My Firefox add-on uses the `browser` namespace and `webextension-polyfill` to make it compatible to Chrome. The following code works fine in Firefox but in Chrome it fails with two errors.

#### Error 1
"The message port closed before a response was received."
![image](https://user-images.githubusercontent.com/18437455/40567421-81e766d4-6075-11e8-8d2b-085888489ddb.png)

#### Error 2
Chrome _requires_ an iconUrl when creating a notification whereas it is _optional_ in Firefox.

**Content script**
```
// Sending a message from the content script...
browser.runtime.sendMessage({text: "Hello, world!"});
```

**Background script**
```
// Waiting for the message in the background script...
function notify(message) {
    browser.notifications.create({
        "type": "basic",
        // Uncomment the following line to make it work in Chrome.        
        //"iconUrl": browser.extension.getURL("/icon.png"),
        "title": "My Title",
        "message": message.text
    });
   // Uncomment the following line to make it work in Chrome.
   //return true;
}

browser.browserAction.onClicked.addListener(() => {
    browser.tabs.executeScript({file: "lib/browser-polyfill.js"});
    browser.tabs.executeScript({file: "content-script.js"});
});

browser.runtime.onMessage.addListener(notify);
```

Is there something that could be fixed or enhanced in `webextension-polyfill`?

**Comment by Rob--W** [comment]
Error 1: Fixed by #140

Error 2:

As (now) documented in the README ( https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox ), the polyfill will not add missing properties. By not automatically putting a dummy value in iconUrl, extension authors can discover that Chrome expects an icon to be set and update the code otherwise.

If anything, the difference should be documented on MDN at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions
