### ISSUE TITLE
Replace API Metadata Database with Runtime Discovery

### ISSUE THREAD

**Issue by DanielHerr** [mozilla/webextension-polyfill#12]
Manually listing functions seems inefficient and unnecessary. It is probably possible to detect whether a function should be converted by whether it returns anything and if it throws a "Invocation of form..." error

**Comment by kmaglione** [comment]
Sorry for the extreme delay.

We need a mix of runtime discovery and API metadata. Without the metadata, we don't know which functions expect a callback, so the only alternative would be error-prone attempts to call them both with and without callbacks, and decide whether to return a promise based on the results.

And besides that, we use the argument metadata to do some basic sanity checking, so that the errors generated by the built-in bindings apply only to the arguments actually passed by the polyfill callers, rather than the combination of the arguments passed by the caller and the arguments passed by the polyfill.
