### ISSUE TITLE
Install the lastest git version with NPM?

### ISSUE THREAD

**Issue by helpermethod** [mozilla/webextension-polyfill#121]
Hi,

is there some way to depend on the latest `master`? I've tried

    $ npm i --save mozilla/webextension-polyfill

but the directory under `node_modules` seems to be empty.

**Comment by Rob--W** [comment]
The Github repo does not include a working version of the polyfill; it needs to be built first.

`package.json` contains a [`files` array](https://docs.npmjs.com/files/package.json#files), consisting of `"dist"` only:
https://github.com/mozilla/webextension-polyfill/blob/76eeeaccc9faaf6403addaf1ee829a8b0b238957/package.json#L6-L8

However, the `dist/` directory does not exist as it needs to be built first.

When I run `npm i mozilla/webextension-polyfill`, then I do get a directory consisting of non-ignored files:

```
./node_modules/webextension-polyfill/package.json
./node_modules/webextension-polyfill/README.md
./node_modules/webextension-polyfill/LICENSE
```

It seems not possible to ignore the automatically ignored files by npm, so if you really want to use the latest master, download the tarball/zip file (or clone the repo) and then install it. But depending on a non-specific version of a library is usually a bad idea, because your project may not build in the future.

**Comment by helpermethod** [comment]
Thanks, I'll stick to the ZIP file then. Any idea when the next version will be released?
