### ISSUE TITLE
runtime.onMessage is broken

### ISSUE THREAD

**Issue by eight04** [mozilla/webextension-polyfill#16]
```
Error in event handler for runtime.onMessage: TypeError: sendResponse is not a function
    at runtime.onMessage.addListener (chrome-extension://oommdnlanbpnfobibbnfmnmobfddkofp/background.js:4:2)
    at onMessage (chrome-extension://oommdnlanbpnfobibbnfmnmobfddkofp/browser-polyfill.js:1338:22)
```
https://github.com/mozilla/webextension-polyfill/blob/master/src/browser-polyfill.js#L314-L328
I'm not sure this is due to API changes or something. The wrapper of listener looks completely nonsense to me. Shouldn't it just invoke the listener directly?
```
      return function onMessage(message, sender, sendResponse) {
        return listener(message, sender, sendResponse);
      };
```

**Comment by kumar303** [comment]
Are you using the [compiled source](https://github.com/mozilla/webextension-polyfill#building)?

**Comment by eight04** [comment]
https://github.com/eight04/ansi-viewer/blob/chrome/polyfill/browser-polyfill.js#L826
Which is compiled and copied from `dist/browser-polyfill.js` and patched by me.

**Comment by kumar303** [comment]
ok, just checking. This has created confusion: https://github.com/mozilla/webextension-polyfill/issues/5

**Comment by joncu01** [comment]
I'm seeing this problem too.  Is there a fix on the way?

**Comment by eight04** [comment]
Currently I patch it myself.
https://github.com/eight04/ansi-viewer/blob/8f6d33f6ee8713ca29d00075c94e9fff89ba04e9/lib/browser-polyfill.js#L828

**Comment by collinsauve** [comment]
Just spent a good hour figuring this out for myself.  Unfortunately different documentation on MDN seems to disagree how this this is supposed to work: 

`runtime.onMessage` (which should probably be considered the source of truth) shows this working with a `sendResponse` callback, returning a boolean indicating if the callback will be invoked asynchronously. 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage

```
function handleMessage(request, sender, sendResponse) {  
  console.log(`content script sent a message: ${request.content}`);
  setTimeout(() => {
    sendResponse({response: "async response from background script"});
  }, 1000);  
  return true;
}

browser.runtime.onMessage.addListener(handleMessage);
```

`tabs.sendMessage` shows this working by returning a promise.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage

```
browser.runtime.onMessage.addListener(request => {
  console.log("Message from the background script:");
  console.log(request.greeting);
  return Promise.resolve({response: "Hi from content script"});
});
```

**Comment by collinsauve** [comment]
@kmaglione please see my above note about MDN discrepancy.  It looks like you wrote this code and added the example in the MDN tabs.sendMessage.  Can you clarify if this should be a callback or a promise?

**Comment by Rob--W** [comment]
FYI I submitted a PR at #22.

**Comment by collinsauve** [comment]
Also added PR #23 on top of #22, which allows multiple async/promise-based handlers as long as only 1 returns a result.

**Comment by Treeeater** [comment]
@eight04 's fix works, however, I slightly modified his fix so that it doesn't touch the Firefox side (retains isThenable part)

      return function onMessage(message, sender, sendResponse) {
        let result = listener(message, sender, sendResponse);

        if (isThenable(result)) {
          result.then(sendResponse, error => {
            console.error(error);
            sendResponse(error);
          });

          return true;
        } else if (result !== undefined) {
          **//sendResponse(result);
	  return result;**
        }
      };

**Comment by carlin-q-scott** [comment]
So... is someone going to merge the PR?

**Comment by rpl** [comment]
My apologies for the late reply, I deferred closing this issue in the last bug triage meeting because I wanted to discuss it again with @kmaglione (mainly to collect additional details and then be able to provide a more complete comment here).

While discussing this issue with @kmaglione it did come out that the polyfill implementation of the `runtime.onMessage` API doesn't provide the `sendResponse` callback on purpose:
the reason is that the `sendResponse` callback is going to be removed from the W3C specs (https://browserext.github.io/browserext/#runtime, the callback is still listed in the current spec draft, but as far as I know, mainly what I did learn from the discussion with Kris, its removal has been discussed and it is going to be removed).

We agreed that this "incompatibility", between the current Firefox implementation and the W3C spec for this API event, should be better highlighted and explained in the API documentation on MDN to prevent confusion about the implementation in the polyfill.

**Comment by eight04** [comment]
So is `sendResponse` deprecated? I thought request-response is a common pattern.

**Comment by collinsauve** [comment]
@rpl can you expand on what the expected usage in WebExtensions be?  I have some guesses as to what you might end up with, is the following correct?

* Any number of listeners can:
    * return `undefined` to indicate no result
* Only 1 listener is allowed to do 1 of:
    * return a non-`Promise` to indicate synchronous result
    * return a `Promise` to indicate asynchronous result.

This means that:
* no more `callback` argument
* no more returning `true` to indicate asynchronous result
* a promise that resolves to `undefined` asynchronously sends an `undefined` result

**Comment by TomerHeber** [comment]
@rpl thank you for the explanation. Is it still true?

Looking in the draft I noticed that it's still:
callback BrowserExtRuntimeOnMessageCallback = void (optional any message,
                                                    BrowserExtRuntimeMessageSender sender,
                                                    BrowserExtRuntimeSendResponseCallback callback);

Though nothing in the draft for BrowserExtRuntimeSendResponseCallback.

**Comment by fosskers** [comment]
Hi there from the future. Since this is the issue linked to from MDN, I decided to post my discovery here. For any Rust folks trying to bind to `browser.runtime.onMessage.addListener` properly, here's how to do it:

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["browser", "runtime"], js_name = "sendMessage")]
    pub async fn send_message(message: JsValue) -> JsValue;

    #[wasm_bindgen(js_namespace = ["browser", "runtime", "onMessage"], js_name = "addListener")]
    pub fn add_listener(handle: &Closure<dyn Fn(JsValue, JsValue) -> Promise>);
}
```
For the `pub async fn send_message`, make sure you have `wasm-bindgen-futures` as a dependency. It auto-converts JS Promises into Rust's `async` system. 

Notice that we're only accepting two arguments to the closure passed to `add_listener`. We completely ignore the `sendMessage` argument and force a `Promise` to be returned, as per the MDN docs.

Downstream, we can add the listener like so:
```rust
    let handle_msg = Closure::wrap(Box::new(move |msg, sender| {
        Promise::resolve(&JsValue::from_str("From background!"))
    }) as Box<dyn Fn(JsValue, JsValue) -> Promise>);
    add_listener(&handle_msg); // The binding we just wrote.
    handle_msg.forget();
```
You're free to do pretty much whatever you want inside the `Box`'d closure, including moving in Rust structures, write log messages, etc. As long as a `Promise` is the final return value. The final `forget` is also critical to insure that the closure isn't dropped on the Rust side before it has a chance to be used on the JS side.

Cheers!
