### ISSUE TITLE
Importing into webpack

### ISSUE THREAD

**Issue by abhijithvijayan** [mozilla/webextension-polyfill#169]
Difference between 
`import browser from "../scripts/vendor/browser-polyfill";` 
and 
`import browser from "webextension-polyfill";`

I noticed in the first method, the final output only includes about 100 lines and the second is around 1000. 

According to docs, there is not much of a difference right?

If there is, which is preferred?

**Comment by rpl** [comment]
@abhijithvijayan could you create a minimal test project that shows the two different behaviors?

I tried both these syntaxes in one of your projects ([kuttUrl-browser-extension](https://github.com/abhijithvijayan/kuttUrl-browser-extension)), because I assumed that is were you have been tried the two approaches above, and the bundles I got are more or less of the same size:

- using `import browser from "../scripts/vendor/browser-polyfill";` the output of `ls -l` shows:

```
88261 background.js
43390 options.js
44987 popup.js
```

- using `import browser from "webextension-polyfill";` the output of `ls -l` shows:

```
88017 background.js
43135 options.js
44721 popup.js
```

By default `import browser from "webextension-polyfill";` should import the js file included in `node_modules/webextension-polyfill/dist/browser-polyfill.js` (as [required by the "main" property in the package.json](https://github.com/mozilla/webextension-polyfill/blob/34a6ab45595dd2c73130f2d9893452f6aa622d85/package.json#L5)), which seems to be basically what you have manually copied into [src/scripts/vendor/browser-polyfill.js](https://github.com/abhijithvijayan/kuttUrl-browser-extension/blob/master/src/scripts/vendor/browser-polyfill.js) in your extension repo, and so the outcome is supposed to be basically the same (as the sizes of the files I generated locally seems to confirm).

> If there is, which is preferred?

When building js bundles with webpack/browserify `import browser from "webextension-polyfill";` is supposed to be the more natural (and then also preferred) way of importing the polyfill.

**Comment by abhijithvijayan** [comment]
@rpl Thanks for testing it out. I'll test it out once again and will get back at you.
