### ISSUE TITLE
runtime.connect

### ISSUE THREAD

**Issue by mchusovlianov** [mozilla/webextension-polyfill#185]
Hi, guys!  I see the method runtime.connect exists in chrome and firefox. But it doesn't look that polyfill returns a promise. I also don't see this method in the api-metadata.json file. Could you clarify this thing, please?

**Comment by Rob--W** [comment]
`runtime.connect` returns a `Port` object. Any method with a non-void return value cannot be turned in a promise, because it would break the API contract.

The `Port` API has two events, `port.onMessage` and `port.onMessage`. It is not obvious what you could expect if the return value were to be a promise.

**Comment by mchusovlianov** [comment]
Thanks @Rob--W  a lot!
