### ISSUE TITLE
Extensions Testing Tips

### ISSUE THREAD

**Issue by KBoyarchuk** [mozilla/webextension-polyfill#189]
I would like to ask a question that concerns not exactly this library, but concerns testing extensions. What is the "best practice" to testing extensions ? What is the ratio of the tests (e2e to unit tests) optimally ? What library for e2e testing is best to choose ? (nightwatch/cypress).

**Comment by Lusito** [comment]
I guess it really depends on the type of extension you have.

I don't think e2e tests can be implemented nicely. I try to write my logic in modules that can be tested independently. Using mocks and spies to assert that it works as expected in various scenarios. I currently have 336 unit tests, some of which are a bit more complex than recommended by some people, but I found this to be the best result for the time I can afford to spend on tests.

Take a look at my tests if you are interested:
https://github.com/Lusito/forget-me-not/tree/develop/test

In this file, I mock every web-extension API that I need for my extension:
https://github.com/Lusito/forget-me-not/blob/develop/test/browserMock.ts

I still don't have everything tested, but it covers a big part of the logic.

The UI of my extension doesn't have any automated tests. I wouldn't know how this could be easily accomplished. I guess if you used react, you could test the UI components more easily, but I decided against react some time ago because of the bad mobile performance. So all my UI tests are currently done manually.

Hope this helps.

**Comment by KBoyarchuk** [comment]
@Lusito Сan you explain to me how to test background script ? How to mock background script **window** object ?

**Comment by Lusito** [comment]
So, here's a simple example:

I have a class `IncognitoWatcher`:
https://github.com/Lusito/forget-me-not/blob/develop/src/background/incognitoWatcher.ts

Its purpose is simple: Add listeners to `browser.tabs.onRemoved/onCreated` so it can keep a map of which tab and which cookie store is incognito (private). On construction it will also query existing tabs in case it was created after tabs where created.

It contains two public methods:
- `hasCookieStore(cookieStoreId: string): bool`
- `hasTab(tabId: number): bool`

They should return true if a cookie store or tabid is registered as incognito.

I also added 2 methods for testing purposes, but they are not used when testing this class. They are only used in other tests to make it easier to set up tests that require an `IncognitoWatcher` dependency injection.

The test for this class can be found here:
https://github.com/Lusito/forget-me-not/blob/develop/test/incognitoWatcherTests.ts

There are two hooks in place:
- beforeEach resets my mock browser instance and creates a new instance of the IncognitoWatcher.
- afterEach ensures the reference gets reset after each test.

Then there are describe/context/it blocks, which describe test scenarios.
For example, the "listeners" block checks if the browser mock instance has been used to add the listeners correctly during construction.

The "hasTabs" section sets up tabs using the mock browser instance (which will call the listeners internally) and then asserts that the hasTab method returns the expected value for the specified values.

The same is done for different scenarios, like having tabs before constructing the object and creating / removing them afterwards.

I've actually never tried to mock the background `window` object. I don't have any usecase where I use the window object in a background script. (you are talking about the global window object, not the web-extensions `browser.windows` API, right? Maybe you can show me some code you want to test and I can write my thoughts about it.

**Comment by KBoyarchuk** [comment]
I'm trying to test background script code

```
isBackgroundScript(script) {
    return new Promise((resolve) => {
      try {
        if (this.browser == browsers.chrome) {
          chrome.runtime.getBackgroundPage(function(backgroundPage) {
            return resolve(script === backgroundPage);
          });
        } else if (this.browser == browsers.firefox) {
          browser.runtime.getBackgroundPage().then(function(backgroundPage) {
            return resolve(script === backgroundPage);
          });
        } else if (this.browser == browsers.edge) {
          browser.runtime.getBackgroundPage(function(backgroundPage) {
            return resolve(script === backgroundPage);
          });
        }
      } catch (err) {
        return resolve(false);
      }

      return false;
    });
  }
```

And I don't understand how to mock **getBackgroundPage** method

**Comment by Lusito** [comment]
Some observations:
- You are using `chrome` instead of `browser` for the chrome case, but not for the other browser.
- You are calling the API browser-specific, but this library should actually solve this for you.
- You are returning the result of resolve.. not sure what this actually does, but it certainly isn't needed.
- You are returning false instead of resolving the promise to false in the last line.
- You are not handling the error case of getBackgroundPage().. not sure if that's a valid case.

A cleaned up version of your method above should look something like this:

```javascript
isBackgroundScript(script) {
    return browser.runtime.getBackgroundPage()
        .then((backgroundPage) => script === backgroundPage)
        .catch(() => false);
}

```

So, if you want to test this code and you can use async functions in your test, it could look like this (pseudocode):

```javascript
async function test() {
    const backgroundPage = 'myBackgroundPage';
    const mockBrowser = {
        runtime: {
            getBackgroundPage: () => Promise.resolve(backgroundPage)
        }
    };
    (global as any).browser = mockBrowser;

    const instance = new MyClass();
    instance.setBrowser(browsers.chrome); // or however you do this

    assert.isTrue(await instance.isBackgroundScript(backgroundPage));
    assert.isFalse(await instance.isBackgroundScript('someOtherPage'));

    // also test the exception case
    mockBrowser.runtime.getBackgroundPage = () => Promise.reject(new Error('test'));
    assert.isFalse(await instance.isBackgroundScript(backgroundPage));
}
```

If you can't use async functions, you'll have to do a bit more:

```javascript
const backgroundPage = 'myBackgroundPage';
const mockBrowser = {
    runtime: {
        getBackgroundPage: () => Promise.resolve(backgroundPage)
    }
};
(global as any).browser = mockBrowser;

const instance = new MyClass();
instance.setBrowser(browsers.chrome); // or however you do this

instance.isBackgroundScript(backgroundPage)
    .then((value) => assert.isTrue(value))
    .catch(() => assert.fail('entered catch'));
instance.isBackgroundScript('someOtherPage')
    .then((value) => assert.isFalse(value))
    .catch(() => assert.fail('entered catch'));

// also test the exception case
mockBrowser.runtime.getBackgroundPage = () => Promise.reject(new Error('test'));
instance.isBackgroundScript(backgroundPage)
    .then((value) => assert.isFalse(value))
    .catch(() => assert.fail('entered catch'));
```
