### ISSUE TITLE
Unable to send message Tab Activated

### ISSUE THREAD

**Issue by tomshaw** [mozilla/webextension-polyfill#207]
I've tried this with vanilla ES6 no web-extension and it works fine. 

```
browser.tabs.onActivated.addListener((info) => {
  console.log('info', info);
  browser.tabs.sendMessage(info.tabId, { message:  'Send message to content.js.' }).then(results => {
    console.log('results', results);
  });
});
```

Currently getting error:   
> _generated_background_page.html:1 Uncaught (in promise) {}
> Promise.then (async)
> (anonymous) @ background.js:1

Manifest looks correct:

```
"content_scripts": [{
    "matches": [
      "*://*/*"
    ],
    "js": [
      "content.js"
    ],
    "run_at": "document_idle",
    "all_frames": false
  }],
  "permissions": [
    "tabs",
    "activeTab",
    "notifications",
    "storage",
    "*://*/*"
  ],
```

**Comment by Rob--W** [comment]
This is not an error in the polyfill, but your extension.

When there is no recipient for the message (i.e. a content script with a `runtime.onMessage` listener), then the sendMessage promise will be rejected. The `{}` from your log is actually an object with error details. If you click on it, you would see:

```
Uncaught (in promise) 
{}
message: "Could not establish connection. Receiving end does not exist."
get message: ƒ ()
__proto__: Object
Promise.then (async)		
(anonymous)	@	background.js:3
```

**Comment by tomshaw** [comment]
Well that's good news. My extension in this case is a default install of [https://github.com/Kocal/vue-web-extension](https://github.com/Kocal/vue-web-extension) with zero code added.

**Comment by Rob--W** [comment]
I see that you've opened a new issue at https://github.com/Kocal/vue-web-extension/issues/494

Still, the answer is the same: Neither the polyfill, nor the boilerplate are at fault. The logic of your test case is flawed, because you're assuming that there is a recipient to the `sendMessage` call. That is not necessarily the case: In Chrome, content scripts are not automatically executed in every tab at install, but only at the next page load. Consequently, most tabs for which `tabs.onActivated` is triggered did not run `content.js`, and therefore any `tabs.sendMessage` call will be rejected. Even if you did reload the page, there are some tabs (e.g. `chrome://extensions/`) where you cannot run content scripts, so you already have to account for errors anyway. You could either use try-catch with `await`,  or use `.then`/`.catch` to handle promise rejections.

**Comment by tomshaw** [comment]
Oddly enough the code works fine without the webextension-polyfill using [chrome-extension-webpack-boilerplate](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate). The functionality is what I expected. When multiple tabs are open, and a tab is clicked/activated background.js informs content.js to refresh. Tonight I'll have more time to look at it. Thanks again for your help/input. :)

**Comment by Rob--W** [comment]
If you don't use the promise API, but `chrome.tabs.sendMessage(tabId, message)` (without callback), then the console won't have an error.

If you add a callback, as in `chrome.tabs.sendMessage(tabId, message, function callback() {})`, then the console will have an error unless the callback checks `chrome.runtime.lastError`.

In a promise-based API, the callback is always used internally (in order to catch the result), hence you're getting an error when the polyfill is used.
