### ISSUE TITLE
Will this project get support for Safari?

### ISSUE THREAD

**Issue by 149segolte** [mozilla/webextension-polyfill#234]
In a WWDC session, Apple announced support for Web extensions on macOS and has provided conversion tools to port extensions. 
The official documentation is at the link: [https://developer.apple.com/documentation/safariservices/safari_web_extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions)

**Comment by Poopooracoocoo** [comment]
it's only for macOS and not iOS fyi

**Comment by 149segolte** [comment]
If the company is making efforts to make this available on macOS then it might lead to it later being ported to iOS.

**Comment by Juraj-Masiar** [comment]
I've been looking into porting my addons to Safari but there is one crucial feature missing - the [`runtime.onMessage`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) API in there doesn't support replying to the message by returning a `Promise`, only by calling the `sendResponse` function which I don't use because it's not recommended and it doesn't exists in this polyfill anymore.

Would implementing this feature for Safari be outside of scope for this polyfill?

**Comment by rpl** [comment]
> I've been looking into porting my addons to Safari but there is one crucial feature missing - the [`runtime.onMessage`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) API in there doesn't support replying to the message by returning a `Promise`, only by calling the `sendResponse` function which I don't use because it's not recommended and it doesn't exists in this polyfill anymore.
> 
> Would implementing this feature for Safari be outside of scope for this polyfill?

I didn't spent yet enough time on tracking down all the differences in the Safari implementation to answer that question in a way as complete and final as I would like, but the following are some initial thoughts:

- Given that Safari should be already providing a Promised API, most of the code in this polyfill isn't really going to be that much useful on Safari, the runtime.onMessage API that @Juraj-Masiar did mention may be the only piece that may be kind of reasonable to polyfill.

- Safari extension contexts do have both `chrome` and `browser` globals, they should be basically aliases and the asynchronous API methods in both of them to be returning a Promise when a callback is not passed (while when there is a callback no promise is returned), and so at the moment this polyfill is likely turning itself into a noop as it does on Firefox, because the `browser` globals is already defined.

- As an additional side note: to officially support another browser, especially for a separate implementation like in this case, the integration tests in this repo should also run in that browser as part of the CI (which is another detail that I haven't digged into yet), it wouldn't be really "supported" without automated tests running on the CI.

About the support for the `sendResponse`, it does print a deprecation warning the first time that it is being used but we didn't remove it from this polyfill: https://github.com/mozilla/webextension-polyfill/blob/b0596ad6165d8e604a68471787f7a67f9e59570d/src/browser-polyfill.js#L377-L386

And so as a short term workaround, sendResponse should work fine across the 3 implementation (Firefox, Safari and Chrome).

**Comment by Juraj-Masiar** [comment]
Thanks @rpl for the info!
I have a huge code base so there is no way I'm gonna refactor it from superior Promises to callbacks :)

But I guess I could write my own simple polyfill, something like this may work:
```typescript
// if (IS_SAFARI) do this:
browser.runtime.onMessage.addListener = new Proxy(browser.runtime.onMessage.addListener, {
  apply: (addListener, thisArg, [handler]) => addListener.call(thisArg, (message, sender, sendResponse) => {
    const result = handler(message, sender, () => { throw Error('Not supported!') });
    if (result instanceof Promise) {
      result.then(sendResponse);
      return true;
    }
  })
});
```
*(not tested yet...)*

**Comment by bcomnes** [comment]
> I've been looking into porting my addons to Safari but there is one crucial feature missing - the [`runtime.onMessage`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) API in there doesn't support replying to the message by returning a `Promise`, only by calling the `sendResponse` function which I don't use because it's not recommended ~and it doesn't exists in this polyfill anymore~.
> 
> Would implementing this feature for Safari be outside of scope for this polyfill?

I ran into this issue this weekend.  Also, I noticed that safari did not fire events for `browser.storage.onChanged.addListener` when you try to `browser.storage.local.set` a storage key to a falsey value like null.  You have to explicitly `browser.storage.local.remove` the key to trigger that event.

**Comment by ivanjeremic** [comment]
Wonder why there is no cross-browser extension framework yet on the market.

**Comment by Rob--W** [comment]
> Wonder why there is no cross-browser extension framework yet on the market.

Years ago there was no cross-browser compatible API. These days we do, and the compatibility is going to improve even further by the recent launch of the WebExtensions Community Group - https://www.w3.org/community/webextensions/2021/06/04/forming-the-wecg/

**Comment by gangsthub** [comment]
> Wonder why there is no cross-browser extension framework yet on the market.

+1000 on that.

I went to https://github.com/fregante/Awesome-WebExtensions hoping to find something new... and nope.

At least Chrome has now shiny new docs on Extensions: https://developer.chrome.com/docs/extensions/

**Comment by csandman** [comment]
@Juraj-Masiar I also have a setup which is using webpack to make a build for each browser, any chance you could elaborate on how you added it using that?  I'm using [webextension-toolbox](https://github.com/webextension-toolbox/webextension-toolbox) and I tried to write a custom webpack script for the safari build using it but couldn't quite get it working right.

**Comment by Juraj-Masiar** [comment]
Just look at the DefinePlugin for Webpack. It will replace all global variables with the specified name. For example this is what I use in the `plugins` array:
```js
      new webpack.DefinePlugin({
        $IS_FIREFOX: IS_FIREFOX || IS_THUNDERBIRD,
        $NOT_FIREFOX: !IS_FIREFOX,
        $IS_THUNDERBIRD: IS_THUNDERBIRD,
        $IS_CHROME: IS_CHROME || IS_SAFARI,   // to make it simple, Safari will inherit existing Chrome codebase
        $IS_SAFARI: IS_SAFARI,
        $IS_EDGE: IS_EDGE,
        $IS_DEV: IS_DEV,
        $IS_PROD: IS_PROD,
        $IS_WEB: IS_WEB,
        $IS_EXT: !IS_WEB,
        $IS_NODE: IS_NODE,
        $IS_TEST: false,
      }),
```
But again, terrible testing, terrible inter-project integration. 
It may be better to use some environment variables, even if it's at the cost of dead code not being removed from the final build.
Actually the more I think about it, the more I want to do it :D. Especially now when I have 100 other things to do :)

**Comment by Juraj-Masiar** [comment]
I have no idea :). I use them only in the backend, but that's integrated in the Nestjs framework I use.
But I would say there must be something for Webpack because people want to environment variables during the build time and they for sure want to drop dead code. I remember I was not able to find it though, but it was years ago.

**Comment by xeenon** [comment]
FYI, Safari does support Promise replies in `onMessage` listeners (for a couple years now) — since Safari 15.4 (Released 2022-03-14).

I think this issue can be closed.

**Comment by Rob--W** [comment]
> FYI, Safari does support Promise replies in `onMessage` listeners (for a couple years now) — since Safari 15.4 (Released 2022-03-14).
> 
> I think this issue can be closed.

Thanks for checking. It is also listed in the BCD: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Runtime/onMessage#browser_compatibility

(to those interested, Chrome also expressed interest in implementing Promise support in onMessage)
