### ISSUE TITLE
icons argument in browser.contextMenus.create() is not supported in chrome

### ISSUE THREAD

**Issue by eugbyte** [mozilla/webextension-polyfill#318]
Specifying the icons argument in `browser.contextMenus.create({icons})` will work only in firefox, but will not work in chrome. In chrome, the context menu will not even render. Once the icons argument is omitted, then can the cross browser functionality work.

As observed in the chrome documentation, https://developer.chrome.com/docs/extensions/reference/contextMenus/#method-create, icons are not supported. However, the icons argument is not handled by webextension-polyfill

**Comment by Rob--W** [comment]
This is out of scope for the library: https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox

> ##API methods or options that are only available when running in Firefox
>
>This library does not provide any polyfill for API methods and options that are only available on Firefox, and they are actually considered out of the scope of this library.

You can do something like this, which works because Chrome will throw when invalid options are passed to the method:

```
let createOptions = {icons};
try {
  browser.contextMenus.create(createOptions);
} catch (e) {
  delete createOptions.icons;
  browser.contextMenus.create(createOptions);
}
```

Note: The `contextMenus.create` API is one of the few APIs that don't return a promise.
