### ISSUE TITLE
HELP: Not able to send message from my vue component to my content script on Firefox

### ISSUE THREAD

**Issue by daveavi** [mozilla/webextension-polyfill#327]
Hello,

Currently I am building an extension that renders a Vue component on the DOM. I am trying to build an extension on both chrome and firefox, and I have recently found the webextension-polyfill library that can help me out with that. To give context,  right now in my background script I am injecting a content script called focus.js:

<img width="427" alt="Screen Shot 2021-07-13 at 12 24 34 PM" src="https://user-images.githubusercontent.com/20130700/125490631-5995a777-d73c-48e1-a847-e7e10873d068.png">
 
Within focus.js, I am creating an Iframe, that renders the vue code I define. In my vue code, I am setting a button that sends a message to focus.js:

<img width="932" alt="Screen Shot 2021-07-13 at 12 24 51 PM" src="https://user-images.githubusercontent.com/20130700/125491257-1224c3fe-3ecb-4680-9e3a-7d408575a755.png">

When I run my extension on chrome, it is able to send a message to my content script perfectly without any errors, but on Firefox I get this error:

<img width="863" alt="Screen Shot 2021-07-13 at 12 39 26 PM" src="https://user-images.githubusercontent.com/20130700/125492003-48536caa-942b-47be-8778-14fe0394f995.png">

I am not sure exactly, I even tried to add focus.js into my list of scripts in my manifest.json, but the same thing happens.

**Comment by Rob--W** [comment]
Looks like you're trying to call the `tabs` extension API from an extension page in a child frame. That's not possible on Firefox because these frames only have access to the same set of APIs as content scripts.

Depending on what you are trying to achieve, you can either send a message to the background script (which can invoke privileged APIs), or use the `postMessage` API (or `MessageChannel` / `MessagePort`) if you want to communicate between the iframe and a content script elsewhere.

In any case, this is not an issue with the polyfill, so I'm closing this ticket.

**Comment by daveavi** [comment]
Awesome thank you this helped a lot!
