### ISSUE TITLE
Thunderbird browser to messenger

### ISSUE THREAD

**Issue by dlh2** [mozilla/webextension-polyfill#343]
Hi, in [Thunderbird WebExtension API](https://webextension-api.thunderbird.net/en/91/) says:

> In Thunderbird, all WebExtension API can be accessed through the browser.* namespace, as with Firefox, but also through the messenger.* namespace, which is a better fit for Thunderbird.

Can we have it the alias messenger? Also I'm pretty sure there are things that messenger namespace doesn't have on browser...

**Comment by Rob--W** [comment]
This repo does not provide types for Typescript.

In my previous comment I already said so, but it seems that you missed it, so I'll repeat it again:
The polyfill provides a `browser` namespace that wraps the `chrome` namespace, so that extensions can use a Promise-based API in Chromium-based browsers that don't support a Promise-based `browser` API.
When the `browser` namespace is present, the polyfill does nothing.

Thunderbird already has the `browser` namespace, so there is no point in using this polyfill in a Thunderbird extension (especially since the extension does presumably not work anywhere else besides Thunderbird; there is no Chromium-based Thunderbird-like application).
