### ISSUE TITLE
How to explore storage?

### ISSUE THREAD

**Issue by ManUtopiK** [mozilla/webextension-polyfill#360]
I use `storage.local.set`.
But, I can't found my storage anywhere with devtools > Application.
Where are stored data?

**Comment by Rob--W** [comment]
It's not possible to use the devtools to easily view the content: https://bugzilla.mozilla.org/show_bug.cgi?id=1292234

You can use `console.log(await browser.storage.local.get(null))` to retrieve all stored information and inspect it.

Not sure why this issue was opened in this repository, as the question has nothing to do with the polyfill.
