### ISSUE TITLE
Support for setShelfEnabled method

### ISSUE THREAD

**Issue by pipriles** [mozilla/webextension-polyfill#381]
Hello, I am currently using version `0.8.2` and I am getting an error trying to use the `.setShelfEnabled` method as documented here:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/setShelfEnabled

This is the error I get:

```
 Error in invocation of downloads.setShelfEnabled(boolean enabled): No matching signature.
```

**Comment by Rob--W** [comment]
`setShelfEnabled` is a Chrome-only API, that doesn't take any callback parameters.
There was a bug report about the lack of callback in Chrome, but that got archived/closed: https://bugs.chromium.org/p/chromium/issues/detail?id=724650

The polyfill doesn't do anything special when an unrecognized (e.g. Chrome-only) method is called. Whatever you invoke the API with is passed to the underlying `chrome.downloads.setShelfEnabled` method. Since Chrome appears to not support any promises or callbacks there, just invoke the method without callback.
