### ISSUE TITLE
globalThis.chrome?.runtime?.id causes Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by erba2061** [mozilla/webextension-polyfill#420]
There still are substantial amount of users with Chromebooks that use old versions of Chrome (v76, v77 etc.). Optional chaining supported from v80.

`globalThis.chrome?.runtime?.id` causes `Uncaught SyntaxError: Unexpected token .`

This check was changed in version 0.10.0. Can we fix it to maintain compatability?
https://github.com/mozilla/webextension-polyfill/blob/0.10.0/src/browser-polyfill.js#L9

**Comment by Rob--W** [comment]
Is it feasible to use an older polyfill version? E.g. 0.9.0 - https://github.com/mozilla/webextension-polyfill/releases/tag/0.9.0 ?

If not, revert this change to get it to work again: https://github.com/mozilla/webextension-polyfill/commit/c12424cf8082020069465864f6b4b85c5aa5738c

**Comment by PoziWorld** [comment]
Since this is a breaking change, it would seem that https://github.com/mozilla/webextension-polyfill/commit/c12424cf8082020069465864f6b4b85c5aa5738c should have triggered a major version bump.
Alternatively, would the team consider transpiling it to ES5?

I develop extensions that are also used by users of Chrome v49 on Windows XP and Firefox v56/Waterfox.

I had to spend a few minutes figuring out why the extension was not working after a seemingly safe upgrade of `webextension-polyfill` to `v0.10.0`, and then look for an existing issue (this one) on GitHub.

**Comment by fregante** [comment]
> should have triggered a major version bump

0.x.0 can contain breaking changes: https://semver.org/#spec-item-4

That's why npm does not automatically update them: https://github.com/npm/node-semver#caret-ranges-123-025-004

> _Many authors treat a 0.x version as if the x were the major "breaking-change" indicator._

**Comment by PoziWorld** [comment]
Good to know, thanks.
