### ISSUE TITLE
storage.session is missing from webextension-polyfill (api-metadata.json)

### ISSUE THREAD

**Issue by TranquilMarmot** [mozilla/webextension-polyfill#424]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/session

(not sure if this issue should be made here or in `DefinitelyTyped`)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/512a2c28ee32918c20aaa37283b0b8984ab2d511/types/webextension-polyfill/namespaces/storage.d.ts#L200-L215

It seems as though `storage.session` is missing from here

**Comment by Rob--W** [comment]
The type issue should be reported upstream. Within this repo, we need to add `session` to https://github.com/mozilla/webextension-polyfill/blob/9398f8cc20ed7e1cc2b475180ed1bc4dee2ebae5/api-metadata.json#L470.

In Firefox `storage.session` is not implemented yet, but we're planning to do so, per https://bugzilla.mozilla.org/show_bug.cgi?id=1687778

**Comment by marci4** [comment]
storage.session is available in firefox 115 (https://bugzilla.mozilla.org/show_bug.cgi?id=1823713)

**Comment by mukunku** [comment]
Can we get session storage support added to the polyfill now, please 🙏🏼

**Comment by andrzejkaras** [comment]
Do you have any ETA for this change? Do you know when in will be available in the polyfill?

**Comment by Rob--W** [comment]
Note: the polyfill does not need source code changes to support Promise in `browser.storage.session`.

In Firefox (and Safari), `browser` already exists and the library does nothing.
In Chrome, `browser` does not exist yet, and the polyfill will fall back to `chrome[apiname]` when `apiname` is not listed in `api-metadata.json`. Because [`storage.session` is MV3-only in Chrome](https://developer.chrome.com/docs/extensions/reference/api/storage#property-session), and all APIs in the Chrome namespace supports Promise in MV3, we don't need to add `storage.session` to `api-metadata.json` for the polyfill to work.

Hence, I'm closing this issue. Any issue you're facing with typing is out of scope for this repository.
