### ISSUE TITLE
Prevent accidentally using a source version of the polyfill

### ISSUE THREAD

**Issue by kumar303** [mozilla/webextension-polyfill#5]
In https://github.com/mdn/webextensions-examples/pull/131 the developer accidentally included the polyfill source file instead of a built source file. RTFM'ing will prevent this from happening in most cases but could we also prevent it in another way? I think it will cut down on invalid bug reports. Ideas:

* log an error that says "this is the wrong file" (or something) if you run the polyfill from source file.
* ... or completely die with an exception when polyfilling from source
* figure out how to strip these errors out in the dist file

**Comment by jeffesquivels** [comment]
Hi,

Guilty as charged (I'm the developer of  mdn/webextensions-examples#131) :grin: .

My five cents: the main source of confusion was that the source file seemed to work fine initially (i.e. I could use the browser namespace in Chrome), so I guess if there is an easy way to make the source file not work at all, that would be good but I also don't think this issue would happen very often (as most extension developers would probably have more experience than me with the JS ecosytem ;-)), plus the changes introduced in commit c8826128550e8d85658460b22318061814206bf4 should be enough to make it clear, at least for me, that the file in the repo is a source file.

Kind regards,

**Comment by rpl** [comment]
This should now be even more explicit:
 starting from [31d778c2](https://github.com/mozilla/webextension-polyfill/commit/31d778c2cde2b15843fbecc5c18392ddb4c2948e#diff-a8dc0200482fd536ca439ed8bcf763c2R22), the polyfill raises an explicit error (Currently "api-metadata.json has not been included in browser-polyfill") when the source file has been wrongly included instead of the built one.
