### ISSUE TITLE
Where is "browser.dom" apis?

### ISSUE THREAD

**Issue by JobaDiniz** [mozilla/webextension-polyfill#580]
The `browser.dom` api is missing: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dom

**Comment by Rob--W** [comment]
`browser.dom` is not implemented in Firefox yet, as the relevant functionality is available on the DOM elements directly.

In Chrome, the polyfill just forwards attempts to access unrecognized namespaces directly to its native implementation, so you wouldn't notice a difference.

In Firefox, because there is no such native implementation, you'd encounter an error if you tried to use it. This aspect is documented at https://github.com/mozilla/webextension-polyfill?tab=readme-ov-file#known-limitations-and-incompatibilities , specifically https://github.com/mozilla/webextension-polyfill?tab=readme-ov-file#issues-that-happen-only-when-running-on-firefox
