### ISSUE TITLE
Wrong Types: sendResponse

### ISSUE THREAD

**Issue by ArthurLobopro** [mozilla/webextension-polyfill#627]
I am migrating a chrome extension to webextension but this snippet of my code gives me a error saying 0 arguments are expected. 

![image](https://github.com/mozilla/webextension-polyfill/assets/64273139/ec9126bc-9eab-4d8d-b773-37e37bf71d41)

And the typing of sendResponse shows:

![image](https://github.com/mozilla/webextension-polyfill/assets/64273139/0a70db41-cd14-40ef-8a69-88a13329a8b6)

Please, can someone correct this type?

**Comment by Rob--W** [comment]
We (the maintainers of webextension-polyfill) are not responsible for this type definition. You should contact the source of your type and request a fix there.

**Comment by ArthurLobopro** [comment]
Ok

**Comment by ba32107** [comment]
I have the same issue. I managed to track this down. It's already fixed in the source repo:
https://github.com/Lusito/webextension-polyfill-ts/blob/2687ea2b007c7a99e0eb19f3790c688ed845f8c3/out/namespaces/runtime.d.ts#L586

However it's still the old version in the repo where the definitions are packaged:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/runtime.d.ts#L452

There is a PR open to merge the fix: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69704

So we gotta wait for this to be merged.
