### ISSUE TITLE
Support page action show_matches/hide_matches

### ISSUE THREAD

**Issue by kewisch** [mozilla/webextension-polyfill#89]
page action now has a nice show/hide_matches feature. It would be great to polyfill this. I could imagine doing so by having the add-on read the manifest.json, pull out the hide_matches lines, and then install a tabs updated and activaged listener that shows/hides the page action.

**Comment by rpl** [comment]
@kewisch it woud be nice but API methods and options that are only available on Firefox are out of the scope of the polyfill, we added a section about it in the new README to explain it: https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox

On Chrome an extension can use the [declarativeContent API](https://developer.chrome.com/extensions/declarativeContent) to achieve it, and so the extension may use runtime discovery to detect when this API is available and use it instead of the Firefox-specific show/hide_matches options.
