### ISSUE TITLE
Use in non-extensions?

### ISSUE THREAD

**Issue by revmischa** [mozilla/webextension-polyfill#98]
It would be nice to use this in web page content scripts and web pages as well, for message passing.

I don't know about other browsers but in chrome you're permitted to use runtime.sendMessage/connect from a web page if an extension ID is provided. Unfortunately there is no such way to provide this and upon import I get the error: 
`Uncaught (in promise) Error: chrome.runtime.connect() called from a webpage must specify an Extension ID (string) for its first argument` in chrome.

In Safari, I get the error:
<img width="598" alt="screen shot 2018-03-26 at 14 24 49" src="https://user-images.githubusercontent.com/245131/37903693-7a0bee60-3101-11e8-99a3-e5e5d4389cea.png">

I'm importing via `import browser from `webextension-polyfill`.

**Comment by Rob--W** [comment]
Chromium is the only browser that supports `chrome.runtime.connect` / `sendMessage` API in web pages (https://developer.chrome.com/extensions/messaging#external-webpage).

This API is not part of the WebExtensions API, so it isn't supported by the polyfill.

**Comment by revmischa** [comment]
The API is used, it's just not exposed. It would be nice to be able to pass a param (extensionID) to it from the interface

**Comment by revmischa** [comment]
connect() appears to be being called from wrapMethod

<img width="1310" alt="screen shot 2018-03-26 at 17 47 09" src="https://user-images.githubusercontent.com/245131/37913556-d1782a3a-311d-11e8-8f31-b2a7bd5fe41f.png">

**Comment by Rob--W** [comment]
The purpose of this polyfill is to be able to write extensions using the WebExtensions API that also work in Chrome (which does not support the Promise-based WebExtensions API via a global `browser` object). If the global `browser` object does not exists, the polyfill creates a `browser` object that forwards all calls to the `chrome` object (and for some methods, it generates a Promisified function).

The polyfill does *not* provide functionality that is not implemented by the host environment, and it does *not* expose methods that are not part of the WebExtensions API.

When you call `browser.runtime.connect({})` with the polyfill, the result is identical to calling `chrome.runtime.connect({})`, because this method already has a return value (so the polyfill does not replace the return value with a `Promise`).

In Safari you are getting the error `Can't find variable: chrome`, because there is no `chrome` object in Safari.

In web pages in Chrome, you are getting `Error: chrome.runtime.connect() called from a webpage must specify an Extension ID (string) for its first argument`, because `chrome.runtime.connect({})` is NOT a supported API in web pages (the error message exactly says what you should be doing instead - i.e. set an extension ID).

If you want to communicate with web pages, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_the_web_page .
