### ISSUE TITLE
All browserAction / pageAction methods support callbacks in Chrome 67+

### ISSUE THREAD

**Issue by Rob--W** [mozilla/webextension-polyfill#99]
Chrome 67+ supports callbacks for all pageAction / browserAction methods, since https://bugs.chromium.org/p/chromium/issues/detail?id=451320#c10

The polyfill should pass a callback for these methods, in order to catch any errors. The logic to do so is described at https://github.com/mozilla/webextension-polyfill/pull/13#issuecomment-277131287

**Comment by rpl** [comment]
We currently call these API method with the callback first (at least the ones that were already identified when we were working on #59), and then if the call with the callback is raising an error, we retry the API call without the callback:

https://github.com/mozilla/webextension-polyfill/blob/a7cbdcc23e069979b81cab87fbfa89c5e7442d30/src/browser-polyfill.js#L135-L156

@Rob--W Do you mind to check if this is working as expected in Chrome 67+? 
and if there are any other API methods that should be marked with the same metadata property (`fallbackToNoCallback`).

So that we can detail more clearly what is actually missing so that we can consider this issue as fixed.

**Comment by Rob--W** [comment]
The patch in Chrome 67 has just landed, so it will take a short while until Canary has the patch.

The following pageAction and browserAction methods are missing from api-metadata.json:

- setBadgeText
- setBadgeBackgroundColor

The following browserAction methods are missing:

- enable
- disable

**Comment by Rob--W** [comment]
Fixed by #125 .
